### ISSUE TITLE
Saunter breaking when used with NSwag > 13.16.1

### ISSUE THREAD

**Issue by cvietor** [tehmantra/saunter#156]
When using Saunter (0.11.0) along with a NSwag version greater than 13.16.1, document generation is broken, propably because of updates in NSwag regarding Namotion.Reflection, used by NJsonSchema.
I suspect this NSwag release to be the interfering issue for saunter:
https://github.com/RicoSuter/NSwag/releases/tag/v13.17.0

```csharp
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.MissingMethodException: Method not found: 'System.String Namotion.Reflection.XmlDocsExtensions.GetXmlDocsRemarks(System.Reflection.MemberInfo, Boolean)'.
         at Saunter.Generation.DocumentGenerator.GenerateOperationFromMethod(MethodInfo method, AsyncApiSchemaResolver schemaResolver, OperationType operationType, AsyncApiOptions options, JsonSchemaGenerator jsonSchemaGenerator, IServiceProvider
serviceProvider)
         at Saunter.Generation.DocumentGenerator.GenerateChannelsFromMethods(IEnumerable`1 asyncApiTypes, AsyncApiSchemaResolver schemaResolver, AsyncApiOptions options, JsonSchemaGenerator jsonSchemaGenerator, IServiceProvider serviceProvider)
         at Saunter.Generation.DocumentGenerator.GenerateChannels(TypeInfo[] asyncApiTypes, AsyncApiSchemaResolver schemaResolver, AsyncApiOptions options, JsonSchemaGenerator jsonSchemaGenerator, IServiceProvider serviceProvider)
         at Saunter.Generation.DocumentGenerator.GenerateDocument(TypeInfo[] asyncApiTypes, AsyncApiOptions options, AsyncApiDocument prototype, IServiceProvider serviceProvider)
         at Saunter.Generation.AsyncApiDocumentProvider.GetDocument(AsyncApiOptions options, AsyncApiDocument prototype)
         at Saunter.AsyncApiMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

I tested and can verify that this issue will be fixed after integrating #154

**Comment by tehmantra** [comment]
This is live in [v0.12.0](https://www.nuget.org/packages/Saunter/0.12.0)
